### ISSUE TITLE
Senior Frontend Engineer

### ISSUE THREAD

**Issue by allanlei** [swaglive/jobs#2]
我們是「帥哥科技」新創團隊，產品是主打私密內容交流的App，使用者可以在 Swag 上訂閱心儀主播的照片影片內容，或者和主播一對一私訊聊天互動。未來 Swag 會朝著成人產業相關的應用和服務為發展主軸。

## 工作內容

* Swag 網頁版。
* Swag 內容管理後台。
* 各種大、中、小型活動頁面。
* Swag 產品官網維護和上新功能。
* 未來可能會將 App 內容擴增到 Web 平台。

## 能力需求

* 精通 JavaScript、CSS 與 HTML
* 相容主流瀏覽器的前端整合開發經驗
* 前端 framework / library 的使用經驗
* 熟悉 React/Vue.js
* 模組化開發經驗
* 熟悉 Git 操作

## 加分

* ES6
* Redux
* Webpack
* Node.js
* CoffeeScript
* Media Source Extension (MSE/EME)
* DASH/HLS Experience
* PubSub
* CI/CD

## 薪資範圍

* 年薪 100 萬新台幣以上

## 工時/特休

* 彈性上下班不打卡，表訂 10:00 至 19:00。
* 平時不鼓勵加班，但若因時程等因素需要加班時加班費依勞基法計算
* 週休二日，依國定假日休假
* 特休極優於勞基法，第一年 14 天，每年增加一天，上限30天
* 地址: 台北市 信義區五段2號14F

## 福利/推薦項

* 年終獎金、中秋節、端午節禮金
* 提供免費午餐 / 零食和飲料
* 提供 MacBook Pro 13" 或 15”，加一個外接顯示器
* 健康檢查補助
* 員工旅遊
* 健身補助
* 在職進修補助

## 聯絡方式

請把履歷寄至 [hr@swag.live](mailto:hr@swag.live)

**Comment by jj009** [comment]
内地的要吗

**Comment by allanlei** [comment]
Please submit an application to hr@swag.live if interested

**Comment by hh83917** [comment]
上班地點在哪?還是remote?

**Comment by freedomlang** [comment]
@allanlei 同问，收大陆的vuer/reacter 吗？

**Comment by allanlei** [comment]
@jj009 @hh83917 @freedomlang 

JD跟新了.  Sorry, remote not available.

> 地址: 台北市 信義區五段2號14F
